name: Release
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      - name: Strip
        run: |
          strip target/release/prometheus-parquet && mv target/release/prometheus-parquet target/release/prometheus-parquet-linux-amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/prometheus-parquet-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-darwin
          default: true
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      - name: Strip
        run: |
          strip target/release/prometheus-parquet && mv target/release/prometheus-parquet target/release/prometheus-parquet-darwin-amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/prometheus-parquet-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}